import { categories, Quote } from "./interfaces.js";

const quote: Quote[] = [
  {
    text: "Your time is limited, don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: categories.inspiration,
    tags: ["time", "life", "individuality"],
  },
  {
    text: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: categories.inspiration,
    tags: ["imagination", "knowledge"],
  },
  {
    text: "I will never stop trying. Because when you find the one, you never give up.",
    author: "Crazy Stupid Love",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I never want to stop making memories with you.",
    author: "Pierre Jeanty",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "And in her smile I see something more beautiful than the stars.",
    author: "Beth Revis​, Across the Universe",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew the second I met you that there was something about you I needed. Turns out it wasn’t something about you at all. It was just you.",
    author: "Jamie McGuire",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Life is the flower for which love is the honey.",
    author: "Victor Hugo",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "All that you are is all that I’ll ever need.",
    author: "Ed Sheeran​, Tenerife Sea",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I don't know any other way of loving.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you as one loves certain dark things, secretly, between the shadow and the soul.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love how she makes me feel like anything is possible, or like life is worth it.",
    author: "500 Days of Summer",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Death cannot stop true love. All it can do is delay it for a while.",
    author: "The Princess Bride",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I want all of you, forever, you and me, every day.",
    author: "Nicholas Sparks, The Notebook",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "What do you want? You want the moon? Just say the word and I'll throw a lasso around it and pull it down.",
    author: "It's A Wonderful Life",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You make me want to be a better man.",
    author: "As Good As It Gets",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew it the very first time I touched her. It was like coming home.",
    author: "Sleepless in Seattle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Love isn’t something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It would be a privilege to have my heart broken by you.",
    author: "The Fault In Our Stars",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It seems right now that all I’ve ever done in my life is making my way here to you.",
    author: "The Bridges of Madison County",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my heart, my life, my one and only thought.",
    author: "Sir Arthur Conan Doyle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love that you are the last person I want to talk to before I go to sleep at night.",
    author: "When Harry Met Sally",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Take love, multiply it by infinity and take it to the depths of forever, and you still have only a glimpse of how I feel for you.",
    author: "Meet Joe Black",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "With the whole world crumbling, we pick this time to fall in love.",
    author: "Ilsa in Casablanca",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking.",
    author: "Leo Tolstoy, Anna Karenina",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my dearest one. My reason for life.",
    author: "Ian McEwan, Atonement",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Brontë, Wuthering Heights",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "If I loved you less, I might be able to talk about it more.",
    author: "Jane Austen, Emma",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You don’t love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    author: "Oscar Wilde",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To be fully seen by somebody, then, and be loved anyhow — this is a human offering that can border on miraculous.",
    author: "Elizabeth Gilbert",
    category: categories.happy,
    tags: ["happy", "love"],
  },
];
