import { categories, Quote } from "./interfaces.js";

const quote: Quote[] = [
  {
    text: "Your time is limited, don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: categories.inspiration,
    tags: ["time", "life", "individuality"],
  },
  {
    text: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: categories.inspiration,
    tags: ["imagination", "knowledge"],
  },
  {
    text: "I will never stop trying. Because when you find the one, you never give up.",
    author: "Crazy Stupid Love",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I never want to stop making memories with you.",
    author: "Pierre Jeanty",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "And in her smile I see something more beautiful than the stars.",
    author: "Beth Revis​, Across the Universe",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew the second I met you that there was something about you I needed. Turns out it wasn’t something about you at all. It was just you.",
    author: "Jamie McGuire",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Life is the flower for which love is the honey.",
    author: "Victor Hugo",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "All that you are is all that I’ll ever need.",
    author: "Ed Sheeran​, Tenerife Sea",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I don't know any other way of loving.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you as one loves certain dark things, secretly, between the shadow and the soul.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love how she makes me feel like anything is possible, or like life is worth it.",
    author: "500 Days of Summer",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Death cannot stop true love. All it can do is delay it for a while.",
    author: "The Princess Bride",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I want all of you, forever, you and me, every day.",
    author: "Nicholas Sparks, The Notebook",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "What do you want? You want the moon? Just say the word and I'll throw a lasso around it and pull it down.",
    author: "It's A Wonderful Life",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You make me want to be a better man.",
    author: "As Good As It Gets",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew it the very first time I touched her. It was like coming home.",
    author: "Sleepless in Seattle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Love isn’t something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It would be a privilege to have my heart broken by you.",
    author: "The Fault In Our Stars",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It seems right now that all I’ve ever done in my life is making my way here to you.",
    author: "The Bridges of Madison County",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my heart, my life, my one and only thought.",
    author: "Sir Arthur Conan Doyle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love that you are the last person I want to talk to before I go to sleep at night.",
    author: "When Harry Met Sally",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Take love, multiply it by infinity and take it to the depths of forever, and you still have only a glimpse of how I feel for you.",
    author: "Meet Joe Black",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "With the whole world crumbling, we pick this time to fall in love.",
    author: "Ilsa in Casablanca",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking.",
    author: "Leo Tolstoy, Anna Karenina",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my dearest one. My reason for life.",
    author: "Ian McEwan, Atonement",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Brontë, Wuthering Heights",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "If I loved you less, I might be able to talk about it more.",
    author: "Jane Austen, Emma",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You don’t love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    author: "Oscar Wilde",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To be fully seen by somebody, then, and be loved anyhow — this is a human offering that can border on miraculous.",
    author: "Elizabeth Gilbert",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
    author: "Unknown",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.",
    author: "Helen Keller",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Of all forms of caution, caution in love is perhaps the most fatal to true happiness.",
    author: "Bertrand Russell, The Conquest of Happiness",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Loved you yesterday, love you still, always have, always will.",
    author: "Elaine Davis",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To love well is the task in all meaningful relationships, not just romantic bonds.",
    author: "bell hooks, All About Love: New Visions",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is always patient and kind. It is never jealous. Love is never boastful or conceited. It is never rude or selfish. It does not take offense and is not resentful. Love takes no pleasure in other people’s sins, but delights in the truth. It is always ready to excuse, to trust, to hope, and to endure whatever comes.",
    author: "1 Corinthians 13:4-7",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
    author: "Buddha",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love takes off the masks we fear we cannot live without and know we cannot live within.",
    author: "James Baldwin, The Fire Next Time",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "All’s fair in love and basketball.",
    author: "Quincy, Love and Basketball",
    category: categories.love,
    tags: ["love", "romance", "basketball"],
  },
  {
    text: "We loved with a love that was more than love.",
    author: "Edgar Allen Poe",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love isn’t something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is a juice with many tastes. Some bitter, others sweet. A wine which has few vineyards.",
    author: "Justice, Poetic Justice",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The practice of love offers no place of safety. We risk loss, hurt, pain. We risk being acted upon by forces outside our control.",
    author: "bell hooks, All About Love: New Visions",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "One is loved because one is loved. No reason is needed for loving.",
    author: "Paulo Coelho, The Alchemist",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is shown more in deeds than in words.",
    author: "Saint Ignatius",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is that condition in which the happiness of another person is essential to your own.",
    author: "Robert A. Heinlein, Stranger in a Strange Land",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "And now these three remain: faith, hope and love. But the greatest of these is love.",
    author: "The Holy Bible: King James Version",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I think... if it is true that there are as many minds as there are heads, then there are as many kinds of love as there are hearts.",
    author: "Leo Tolstoy, Anna Karenina",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is like the wind, you can't see it but you can feel it.",
    author: "Nicholas Sparks, A Walk to Remember",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "In love there are two things: bodies and words.",
    author: "Joyce Carol Oates",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Continue to share your heart with people even if it has been broken.",
    author: "Amy Poehler",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is such a powerful force. It’s there for everyone to embrace-that kind of unconditional love for all of humankind. That is the kind of love that impels people to go into the community and try to change conditions for others, to take risks for what they believe in.",
    author: "Coretta Scott King",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To love is to recognize yourself in another.",
    author: "Eckhart Tolle",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To be fully seen by somebody, then, and be loved anyhow - this is a human offering that can border on miraculous.",
    author: "Elizabeth Gilbert",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love isn't something natural. Rather it requires discipline, concentration, patience, faith, and the overcoming of narcissism. It isn't a feeling, it is a practice.",
    author: "Eric Fromm",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There is always some madness in love. But there is also always some reason in madness.",
    author: "Friedrich Nietzsche",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There's all kinds of reasons that you fall in love with one person rather than another: Timing is important. Proximity is important. Mystery is important.",
    author: "Helen Fisher",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Passion makes the world go 'round. Love just makes it a safer place.",
    author: "Ice-T",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I believe in love. I think it just hits you and pulls the rug out from underneath you and, like a baby, demands your attention every minute of the day.",
    author: "Jodi Picoult",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When you find that one that's right for you, you feel like they were put there for you, you never want to be apart.",
    author: "Joe Manganiello",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When you're lucky enough to meet your one person, then life takes a turn for the best. It can't get better than that.",
    author: "John Krasinski",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You know it's love when all you want is that person to be happy, even if you're not part of their happiness.",
    author: "Julia Roberts",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love has nothing to do with what you are expecting to get — only with what you are expecting to give — which is everything.",
    author: "Katharine Hepburn",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Where there is great love, there are always miracles.",
    author: "Willa Cather",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "In real love, you want the other person's good. In romantic love, you want the other person.",
    author: "Margaret Anderson",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Have enough courage to trust love one more time and always one more time.",
    author: "Maya Angelou",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "True love is singing karaoke Under Pressure and letting the other person sing the Freddie Mercury part.",
    author: "Mindy Kaling",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Where we love is home – home that our feet may leave, but not our hearts.",
    author: "Oliver Wendell Holmes Sr.",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.",
    author: "Oprah Winfrey",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I love you not only for what you are, but for what I am when I am with you.",
    author: "Roy Croft",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I'm just a big believer in 'you must love yourself before you can love anybody else' and I think for me that breeds the most inspired relationships.",
    author: "Scarlett Johansson",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When you are missing someone, time seems to move slower, and when I'm falling in love with someone, time seems to be moving faster.",
    author: "Taylor Swift",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You found parts of me I didn't know existed and in you I found a love I no longer believed was real.",
    author: "Unknown",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love makes your soul crawl out from its hiding place.",
    author: "Zora Neale Hurston",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There is only one happiness in this life, to love and be loved.",
    author: "George Sand",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I swear I couldn't love you more than I do right now, and yet I know I will tomorrow.",
    author: "Leo Christopher",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love does not dominate; it cultivates.",
    author: "Johann Wolfgang von Goethe",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The only thing we never get enough of is love; and the only thing we never give enough of is love.",
    author: "Henry Miller",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "It is a curious thought, but it is only when you see people looking ridiculous that you realize just how much you love them.",
    author: "Agatha Christie",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is the whole thing. We are only pieces.",
    author: "Rumi",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "True love comes quietly, without banners or flashing lights. If you hear bells, get your ears checked.",
    author: "Erich Segal",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Life is the flower for which love is the honey.",
    author: "Victor Hugo",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You always gain by giving love.",
    author: "Reese Witherspoon​",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "All that you are is all that I’ll ever need.",
    author: "Ed Sheeran",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I love her, and that’s the beginning and end of everything.",
    author: "F. Scott Fitzgerald ​​",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love recognizes no barriers.",
    author: "Maya Angelou​",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is composed of a single soul inhabiting two bodies.",
    author: "Aristotle",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "We are most alive when we're in love.",
    author: "John Updike",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There is no charm equal to tenderness of heart.",
    author: "Jane Austen",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The heart has its reasons of which reason knows nothing.",
    author: "Blaise Pascal",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is friendship that has caught fire.",
    author: "Ann Landers",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love yourself first and everything falls into line.",
    author: "Lucille Ball",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You can't blame gravity for falling in love.",
    author: "Albert Einstein",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "If you find someone you love in your life, then hang on to that love.",
    author: "Princess Diana",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I think I'd miss you even if we never met.",
    author: "The Wedding Date",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I fell in love the way you fall asleep: slowly, and then all at once.",
    author: 'John Green, "The Fault in Our Stars"',
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: 'A simple "I love you" means more than money.',
    author: "Frank Sinatra",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Everything I do, I do it for you.",
    author: "Bryan Adams",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You don't marry someone you can live with — you marry someone you cannot live without.",
    author: "Unknown",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I want all of you, forever, you and me, every day.",
    author: 'Nicholas Sparks, "The Notebook"',
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To me, you are perfect.",
    author: "Love Actually",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "If you live to be a hundred, I want to live to be a hundred minus one day, so I never have to live without you.",
    author: "Winnie the Pooh",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "True love stories never have endings.",
    author: "Richard Bach",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There's nothing that I wouldn't do to make you feel my love.",
    author: "Bob Dylan",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "'Tis better to have loved and lost, than never to have loved at all.",
    author: "Alfred, Lord Tennyson",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is something sent from heaven to worry the hell out of you.",
    author: "Dolly Parton",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To be brave is to love someone unconditionally, without expecting anything in return.",
    author: "Madonna",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You know you're in love when you can't fall asleep because the reality is finally better than your dreams.",
    author: "Dr. Seuss",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I love being married. It's so great to find one special person you want to annoy for the rest of your life.",
    author: "Rita Rudner",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The best thing to hold onto in life is each other.",
    author: "Audrey Hepburn",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You should be kissed and often, and by someone who knows how.",
    author: "Gone With the Wind",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "That's why they call them crushes. If they were easy, they'd call them something else.",
    author: "Sixteen Candles",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I like you very much. Just as you are.",
    author: "Bridget Jones's Diary",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Personally, I love a great love story.",
    author: "Meghan Markle",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is the flower; you've got to let it grow.",
    author: "John Lennon",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Maybe I don’t know that much but I know this much is true, I was blessed because I was loved by you.",
    author: "Celine Dion",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
    author: "When Harry Met Sally",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love loves to love love.",
    author: "James Joyce",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Nobody has ever measured, not even poets, how much the heart can hold.",
    author: "Zelda Fitzgerald",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is an endless act of forgiveness.",
    author: "Beyoncé",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "All you need is love. But a little chocolate now and then doesn't hurt.",
    author: "Charles M. Schulz",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "First and foremost, self-love, and then give love away.",
    author: "Katy Perry",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The smile is the beginning of love.",
    author: "Mother Teresa",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Some love stories aren't epic novels. Some are short stories, but that doesn't make them any less filled with love.",
    author: "Sex and the City",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "All you need is love.",
    author: "The Beatles",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love was made for me and you.",
    author: "Nat King Cole",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I’d never lived before your love.",
    author: "Kelly Clarkson",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "At the touch of love everyone becomes a poet.",
    author: "Plato",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "In all the world, there is no love for you like mine.",
    author: "Maya Angelou",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I wanted it to be you. I wanted it to be you so badly.",
    author: "You've Got Mail",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You had me at hello.",
    author: "Jerry Maguire",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.",
    author: 'Paulo Coelho, "The Alchemist"',
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To feel the love of people whom we love is a fire that feeds our life.",
    author: "Pablo Neruda",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Never love anyone who treats you like you're ordinary.",
    author: "Oscar Wilde",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Sometimes it's a form of love just to talk to somebody that you have nothing in common with and still be fascinated by their presence.",
    author: "David Byrne",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
    author: "Rumi",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When you love someone, you love the person as they are, and not as you'd like them to be.",
    author: "Leo Tolstoy",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "When I saw you I fell in love, and you smiled because you knew.",
    author: "Arrigo Boito",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
    author: "Victor Hugo",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The greatest thing you'll ever learn is to love and be loved in return.",
    author: "Nat King Cole",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You are my sun, my moon and all my stars.",
    author: "E. E. Cummings",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You don't love someone because they're perfect, you love them in spite of the fact that they're not.",
    author: 'Jodi Picoult, "My Sister\'s Keeper"',
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Brontë",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Oh, how a quiet love can drown out every fear.",
    author: "Jessica Katoff",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I have decided to stick to love; hate is too great a burden to bear.",
    author: "Martin Luther King, Jr.",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I’ve tried so many times to think of a new way to say it, and it’s still I love you.",
    author: "Zelda Fitzgerald",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.",
    author: "Mr. Darcy, 'Pride and Prejudice'",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "If I had a flower for every time I thought of you... I could walk through my garden forever.",
    author: "Alfred Tennyson",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "We love the things we love for what they are.",
    author: "Robert Frost",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
    author: "Sarah Dessen, The Truth About Forever",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "We accept the love we think we deserve.",
    author: "Stephen Chbosky, The Perks of Being a Wallflower",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Our greatest joy and our greatest pain come in our relationships with others.",
    author: "Stephen R. Covey",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Relationships are like glass. Sometimes it’s better to leave them broken than try to hurt yourself putting it back together.",
    author: "Unknown",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It is sad not to love, but it is much sadder not to be able to love.",
    author: "Miguel de Unamuno",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Some people are going to leave, but that’s not the end of your story. That’s the end of their part in your story.",
    author: "Faraaz Kazi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It’s amazing how someone can break your heart and you can still love them with all the little pieces.",
    author: "Ella Harper",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is one pain, I often feel, which you will never know. It’s caused by the absence of you.",
    author: "Ashleigh Brilliant",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "When you think you’re first falling in love, just then you realize you’re falling out of love.",
    author: "David Grayson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Since I can’t be with you right now I will have to be content just dreaming about when we will be together again.",
    author: "Susan Polis Schutz",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Falling in love is like holding a candle. Initially it lightens up the world around you. Then it starts melting and hurts you. Finally it goes off and everything is darker than ever and all you are left with is the…BURN!",
    author: "Syed Arshad",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I wonder if I could take back every ‘I love you’ ever said to you, would I do it?",
    author: "Faraaz Kazi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love never dies a natural death. It dies because we don’t know how to replenish its source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of withering, of tarnishing.",
    author: "Anaïs Nin",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Tis better to have loved and lost than never to have loved at all.",
    author: "Alfred Lord Tennyson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The walls we build around us to keep sadness out also keep out the joy.",
    author: "Jim Rohn",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is a time for departure, even when there’s no certain place to go.",
    author: "Tennessee Williams",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Tears come from the heart and not from the brain.",
    author: "Leonardo da Vinci",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It hurts to leave a light on for nobody.",
    author: "Graham Foust",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Breathing is hard. When you cry so much, it makes you realize that breathing is hard.",
    author: "David Levithan",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "He taught me how to love, but not how to stop.",
    author: "Unknown",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You cannot protect yourself from sadness without protecting yourself from happiness.",
    author: "Jonathan Safran Foer",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It will never rain roses: when we want to have more roses, we must plant more roses.",
    author: "George Eliot",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "For all sad words of tongue and pen, the saddest are these, ‘It might have been.",
    author: "John Greenleaf Whittier",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sadness is but a wall between two gardens.",
    author: "Khalil Gibran",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Don’t cry because it’s over, smile because it happened.",
    author: "Unknown",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.",
    author: "Henry Wadsworth Longfellow",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Nothing takes the taste out of peanut butter quite like unrequited love.",
    author: "Charlie Brown",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "If we must part forever, Give me but one kind word to think upon, And please myself with, while my heart’s breaking.",
    author: "Thomas Otway",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "When you think your first falling in love, just then you realize you’re falling out of love.",
    author: "David Grayson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You can close your eyes to things you don’t want to see, but you can’t close your heart to things you don’t want to feel.",
    author: "Johnny Depp",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sad things happen. They do. But we don’t need to live sad forever.",
    author: "Mattie Stepanek",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The walls we build around us to keep sadness out also keeps out the joy.",
    author: "Jim Rohn",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Things change. And friends leave. Life doesn’t stop for anybody.",
    author: "Stephen Chbosky",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You make me feel like a firefly. Trapped in a belljar; starved for love.",
    author: "Ayushee Ghoshal",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Part of me aches at the thought of her being so close yet so untouchable.",
    author: "Nicholas Sparks",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It is better to have loved and lost, than never to have loved at all.",
    author: "Samuel Butler",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Ever has it been that love knows not its own depth until the hour of separation.",
    author: "Kahlil Gibran",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "He was acting like our kiss had broken him, and his reaction was breaking me.",
    author: "Shannon A. Thompson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love lies in those unsent drafts in your mailbox. Sometimes you wonder whether things would have been different if you’d clicked ‘Send’.",
    author: "Faraaz Kazi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Don’t let the scars on your heart define the way you love.",
    author: "Laura Chouette",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You can’t buy love, but you can pay heavily for it.",
    author: "Henny Youngman",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is nothing more painful in this world than to be in love with something that never can be.",
    author: "Laura Chouette",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Just let me keep the last piece of my heart before you tear it all apart.",
    author: "Lykke Li",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes temporary feels like a blessing in a world where love only lasts a second.",
    author: "Laura Chouette",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Never make a decision when you are upset, sad, jealous or in love.",
    author: "Mario Teguh",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is love of course. And then there’s life, its enemy.",
    author: "Jean Anouilh",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love isn’t there to make us happy. I believe it exists to show us how much we can endure.",
    author: "Hermann Hesse",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Nothing is worse than when someone who’s supposed to love you just leaves.",
    author: "Ava Dellaira",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I wish I could give you my pain just for one moment so you can understand how much you hurt me.",
    author: "Mohsen El-Guindy",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I’ve lost love. I’ve tried to reclaim a lost love and didn’t know how to do it.",
    author: "Sam Worthington",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "As the light begins to intensify, so does my misery, and I wonder how it is possible to hurt so much when nothing is wrong.",
    author: "Tabitha Suzuma",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is a sacredness in tears. They are not the mark of weakness, but of power. They speak more eloquently than ten thousand tongues. They are the messengers of overwhelming grief, of deep contrition, and of unspeakable love.",
    author: "Washington Irving",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It’s sad when someone you know becomes someone you knew.",
    author: "Henry Rollins",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Let my soul smile through my heart and my heart smile through my eyes, that I may scatter rich smiles in sad hearts.",
    author: "Paramahansa Yogananda",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I cannot eat, I cannot drink; the pleasures of youth and love are fled away: there was a good time once, but now that is gone, and life is no longer life.",
    author: "Plato",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Your absence has gone through me\nLike thread through a needle\nEverything I do is stitched with its color.",
    author: "W.S. Merwin",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "How could an Angel break my heart? Why didn’t he catch my falling star? I wish I didn’t wish so hard. Maybe I wished our love apart.",
    author: "Tony Braxton",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You ruin your love because you don’t think you deserve anything good.",
    author: "Warsan Shire",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The word ‘happy’ would lose its meaning if it were not balanced by sadness.",
    author: "Carl Jung",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "First, accept sadness. Realize that without losing, winning isn’t so great.",
    author: "Alyssa Milano",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You can never control who you fall in love with, even when you’re in the most sad, confused time of your life. You don’t fall in love with people because they’re fun. It just happens.",
    author: "Kirsten Dunst",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The good times of today, are the sad thoughts of tomorrow.",
    author: "Bob Marley",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "For all sad words of tongue and pen, the saddest are these, “It might have been.”",
    author: "John Greenleaf Whittier",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sadness is also a kind of defence.",
    author: "Ivo Andric",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "When one door closes another door opens; but we so often look so long and so regretfully upon the closed door, that we do not see the ones which open for us.",
    author: "Alexander Graham Bell",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Rather than crying & craving for those who left our path during dark moments of our life, lets spend some time to thank them who stood and helped us to pass those dark paths.",
    author: "Nehali Lalwani",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "People love each other for many reasons, not all of them good […]. They love each other because it’s easy. Or because they’re used to it. Or because they’ve given up. Or because they’re scared.",
    author: "Nathan Hill",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Tears shed for another person are not a sign of weakness. They are a sign of a pure heart.",
    author: "José N. Harris",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Tears are words that need to be written.",
    author: "Paulo Coelho",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Percy let me go, she croaked. You can’t pull me up. Never",
    author: "Rick Riordan",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Who would have listened to his tales of woe when his love was the flickering lamp over his own decaying tomb?",
    author: "Faraaz Kazi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "And in the end, I said you would love me. We’re in the end and there’s only one of us here.",
    author: "Dominic Riccitello",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I’ll love you even when I can’t\nI’ll love you even when I shouldn’t",
    author: "Colleen Hoover",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Me wondering why they don’t say nothing about a kiss being salty as a tear.",
    author: "Lindsay Hunter",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes you don’t realize how much you care for someone until they stop caring for you.",
    author: "Unknown",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "There is no disguise which can hide love for long where it exists, or simulate it where it does not.",
    author: "La Rochefoucauld",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Hearts are not had as a gift, But hearts are earned…",
    author: "William Butler Yeats",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The worst feeling in the world is knowing you’ve done everything you can to show someone you love them, and yet they still choose someone else over you.",
    author: "Bernajoy Vaal",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "So it’s true, when all is said and done, grief is the price we pay for love.",
    author: "E.A. Bucchianeri",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Hearts can break. Yes, hearts can break. Sometimes I think it would be better if we died when they did, but we don’t.",
    author: "Stephen King",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The worst feeling is not being lonely. It’s when someone makes you feel special, then suddenly leaves you and you have to pretend you don’t mind at all.",
    author: "Nishan Panwar",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Hearts are breakable. Even when you heal, you’re never what you were before.",
    author: "Cassandra Clare",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Among my stillness was a pounding heart.",
    author: "Shannon A. Thompson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I felt her absence. it was like waking up one day with no teeth in your mouth. you wouldn’t need to run to the mirror to know they were gone.",
    author: "James Dashner",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Missing someone special to you bring tears to your eyes, but remembering all the good times you had brings a smile to your face.",
    author: "Nishan Panwar",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I just wanted to tell you that I understand if you go. It’s okay if you have to leave us. It’s okay if you want to stop fighting.",
    author: "Gayle Forman",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I wore your promise on my finger for one year. I’ll wear your name on my heart till I die. Because you were my boy, you were my only boy forever.",
    author: "Coco J. Ginger",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes we get sad about things and we don’t like to tell other people that we are sad about them. We like to keep it a secret. Or sometimes, we are sad but we really don’t know why we are sad, so we say we aren’t sad but we really are.",
    author: "Mark Haddon",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The sweetest part of being a couple is sharing your life with someone else. But my life, evidently, had not been good enough to share.",
    author: "Charlaine Harris",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "When the person you love can’t see your love for them beneath the painful things you say when they reject you, remember this: Love is blind.",
    author: "Shannon L. Alder",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Tears are words the mouth can’t say nor can the heart bear.",
    author: "Joshua Wisenbaker",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Every night, I laid awake with your memories flooding through my eyes with the hope to be with you when sleep arrived.",
    author: "Anmol Rawat",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "One day you’re going to remember me and how much I loved you… then you’re gonna hate yourself for letting me go.",
    author: "Aubrey Drake Graham",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Death leaves a heartache no one can heal, love leaves a memory no one can steal.",
    author: "Richard Puz",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Don’t cry when the sun is gone, because the tears won’t let you see the stars.",
    author: "Violeta Parra",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love is the most beautiful of dreams and the worst of nightmares.",
    author: "Aman Jassal",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The heart was made to be broken.",
    author: "Oscar Wilde",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "A broken heart is just the growing pains necessary so that you can love more completely when the real thing comes along.",
    author: "J.S.B. Morse",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The clouds wept when my heart sang a song of sorrow.",
    author: "Sonya Watson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Unrequited love is the infinite curse of a lonely heart.",
    author: "Christina Westover",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes it takes a heartbreak to shake us awake and help us see we are worth so much more than we’re settling for.",
    author: "Mandy Hale",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The way to my heart was shattered when you left me, but I was glad because your memories were invulnerable, locked inside my heart.",
    author: "Anmol Rawat",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It is strange how often a heart must be broken before the years can make it wise.",
    author: "Sara Teasdale",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I understand that if you have never suffered a broken heart, then you have never really known what it is to truly be alive.",
    author: "Patti Roberts",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I’d rather love a million times and have my heart broken every time, than hold a permanently empty heart forever.",
    author: "H.C. Paye",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I know my heart will never be the same but I’m telling myself I’ll be okay.",
    author: "Sara Evans",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The shattering of a heart when being broken is the loudest quiet ever.",
    author: "Carroll Bryant",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes we hurt the ones we love, but hurting ourselves to avoid it doesn’t make it better.",
    author: "Shannon A. Thompson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love is never supposed to hurt. Love is supposed to heal, to be your haven from misery, to make living worthwhile.",
    author: "Mia Asher",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It’s the love that goes through the hardest trials and survives that’s worth having.",
    author: "Katie Ashley",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Just because we can’t be together doesn’t mean I don’t love you.",
    author: "Cecily von Ziegesar",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I was never one to patiently pick up broken fragments and glue them together again and tell myself that the mended whole was as good as new. What is broken is broken — and I’d rather remember it as it was at its best than mend it and see the broken places as long as I lived.",
    author: "Margaret Mitchell",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The flame of love is now just a cold loneliness.",
    author: "Uniek Swain",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "It is better to have loved and lost than never to have loved at all.",
    author: "Samuel Butler",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Let your tears come. Let them water your soul.",
    author: "Eileen Mayhew",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "To live in a hallucination of being loved is more painful than rejection.",
    author: "Vinaya Panicker",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Life goes on… with or without you.",
    author: "Faraaz Kazi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "To fall in love is awfully simple, but to fall out of love is simply awful.",
    author: "Bess Myerson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "To the world, you may be one person, but to one person you are the world.",
    author: "Bill Wilson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Every heart needs a cutting part sharper than a blade to stab agony",
    author: "Munia Khan",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The worst feeling is to be ignored once, then twice, then again and again by someone you consider precious.",
    author: "Betsy Kenton",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Pleasure of love lasts but a moment. Pain of love lasts a lifetime.",
    author: "Bette Davis",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "To live in this world you must be able to do three things: to love what is mortal; to hold it against your bones knowing your own life depends on it; and when the time comes to let it go, to let it go.",
    author: "Mary Oliver",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "He is not a lover who does not love forever.",
    author: "Euripides",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The hottest love has the coldest end.",
    author: "Socrates",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I was born when you kissed me. I died when you left me. I lived a few weeks while you loved me.",
    author: "Humphrey Bogart",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love seeketh not itself to please, nor for itself hath any care, but for another gives its ease, and builds a Heaven in Hell’s despair.",
    author: "William Blake",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love is or it ain’t. Thin love ain’t love at all.",
    author: "Toni Morrison",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes you need to run away just to see who will come after you.",
    author: "Lisa Page Brooks",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "When people can walk away from you: Let them walk.",
    author: "T. D. Jakes",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love is hard to find, hard to keep, and hard to forget.",
    author: "Alysha Speer",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "This is what it felt like to have a broken heart. It felt less like a cracking down the middle and more like she had swallowed it whole and it sat bruised and bleeding in the pit of her stomach.",
    author: "Wendy Wunder",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I did the searching and remembering, She did the disappearing and the forgetting.",
    author: "Ann Brashares",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "She had tricked him. She had made him leave his old self behind and come into her world, and then before he was really at home in it but too late to go back, she had left him stranded there–like an astronaut wandering about on the moon. Alone.",
    author: "Katherine Paterson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love must not suffocate but breathe on its own.",
    author: "Soraya Naomi",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Envy hurt exponentially more than heartbreak because your soul was torn in two, half soaring with happiness for another person, half mired in a well of selfpity and pain.",
    author: "Diana Peterfreund",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "If you love something, let it go…",
    author: "Karen Shreck",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love can sometimes be magic..but magic can sometimes ..just be an illusion.",
    author: "Javan",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes waiting is the hardest thing of all.",
    author: "Luanne Rice",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I love you forever. I am sorry I cannot love you now.",
    author: "Nick Harkaway",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Sometimes, when one person is missing, the whole world seems depopulated.",
    author: "Lamartine",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love hurts, if rejected or betrayed. If not at all, then love is all around.",
    author: "Toba Beta",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "My love lies bleeding.",
    author: "Thomas Campbell",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The way to love anything is to realize that it might be lost.",
    author: "G.K. Chesterton",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love reckons hours for months, and days for years; and every little absence is an age.",
    author: "John Dryden",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Love bleeds you dry until the red organ ceases to beat.",
    author: "Sonya Watson",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "All my memories still smell of you!",
    author: "Avijeet Das",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "The more I know of the world, the more I am convinced that I shall never see a man whom I can really love.",
    author: "Jane Austen",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "But love is not a joke, it also means sharing someone else’s pain.",
    author: "Banana Yoshimoto",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "You flew off with the wings of my heart and left me flightless.",
    author: "Terri Guillemets",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Every time your heart is broken, a doorway cracks open to a world full of new beginnings, new opportunities.",
    author: "Patti Roberts",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Regret not that you suffer in love, regret if you don’t.",
    author: "Abhijit Naskar",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "We were inseparable once. And today I hate even thinking about you.",
    author: "Garima Soni",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "Only the one you will love will have the ability to hurt you.",
    author: "Purvi Mehta",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  {
    text: "I don’t mind the pain you give me. As long as you promise to heal me with your love.",
    author: "Garima Soni",
    category: categories.sad,
    tags: ["sad", "depressed", "depression"],
  },
  // {
  //   text: "",
  //   author: "",
  //   category: categories.sad,
  //   tags: ["sad", "depressed", "depression"],
  // },
  // Quote 150 - For Ducko is contiune adding these love quotes...
];
