import { categories, Quote } from "./interfaces.js";

const quote: Quote[] = [
  {
    text: "Your time is limited, don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: categories.inspiration,
    tags: ["time", "life", "individuality"],
  },
  {
    text: "Imagination is more important than knowledge.",
    author: "Albert Einstein",
    category: categories.inspiration,
    tags: ["imagination", "knowledge"],
  },
  {
    text: "I will never stop trying. Because when you find the one, you never give up.",
    author: "Crazy Stupid Love",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I never want to stop making memories with you.",
    author: "Pierre Jeanty",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "And in her smile I see something more beautiful than the stars.",
    author: "Beth Revis​, Across the Universe",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew the second I met you that there was something about you I needed. Turns out it wasn’t something about you at all. It was just you.",
    author: "Jamie McGuire",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Life is the flower for which love is the honey.",
    author: "Victor Hugo",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "All that you are is all that I’ll ever need.",
    author: "Ed Sheeran​, Tenerife Sea",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I don't know any other way of loving.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love you as one loves certain dark things, secretly, between the shadow and the soul.",
    author: "Pablo Neruda",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love how she makes me feel like anything is possible, or like life is worth it.",
    author: "500 Days of Summer",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Death cannot stop true love. All it can do is delay it for a while.",
    author: "The Princess Bride",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I want all of you, forever, you and me, every day.",
    author: "Nicholas Sparks, The Notebook",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "What do you want? You want the moon? Just say the word and I'll throw a lasso around it and pull it down.",
    author: "It's A Wonderful Life",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To love and be loved is to feel the sun from both sides.",
    author: "David Viscott",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You make me want to be a better man.",
    author: "As Good As It Gets",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I knew it the very first time I touched her. It was like coming home.",
    author: "Sleepless in Seattle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Love isn’t something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It would be a privilege to have my heart broken by you.",
    author: "The Fault In Our Stars",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "It seems right now that all I’ve ever done in my life is making my way here to you.",
    author: "The Bridges of Madison County",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my heart, my life, my one and only thought.",
    author: "Sir Arthur Conan Doyle",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "I love that you are the last person I want to talk to before I go to sleep at night.",
    author: "When Harry Met Sally",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Take love, multiply it by infinity and take it to the depths of forever, and you still have only a glimpse of how I feel for you.",
    author: "Meet Joe Black",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "With the whole world crumbling, we pick this time to fall in love.",
    author: "Ilsa in Casablanca",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking.",
    author: "Leo Tolstoy, Anna Karenina",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You are my dearest one. My reason for life.",
    author: "Ian McEwan, Atonement",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Brontë, Wuthering Heights",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "If I loved you less, I might be able to talk about it more.",
    author: "Jane Austen, Emma",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Being deeply loved by someone gives you strength while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "You don’t love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    author: "Oscar Wilde",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "To be fully seen by somebody, then, and be loved anyhow — this is a human offering that can border on miraculous.",
    author: "Elizabeth Gilbert",
    category: categories.happy,
    tags: ["happy", "love"],
  },
  {
    text: "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
    author: "Unknown",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.",
    author: "Helen Keller",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Of all forms of caution, caution in love is perhaps the most fatal to true happiness.",
    author: "Bertrand Russell, The Conquest of Happiness",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Loved you yesterday, love you still, always have, always will.",
    author: "Elaine Davis",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To love well is the task in all meaningful relationships, not just romantic bonds.",
    author: "bell hooks, All About Love: New Visions",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is always patient and kind. It is never jealous. Love is never boastful or conceited. It is never rude or selfish. It does not take offense and is not resentful. Love takes no pleasure in other people’s sins, but delights in the truth. It is always ready to excuse, to trust, to hope, and to endure whatever comes.",
    author: "1 Corinthians 13:4-7",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "You, yourself, as much as anybody in the entire universe, deserve your love and affection.",
    author: "Buddha",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love takes off the masks we fear we cannot live without and know we cannot live within.",
    author: "James Baldwin, The Fire Next Time",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "All’s fair in love and basketball.",
    author: "Quincy, Love and Basketball",
    category: categories.love,
    tags: ["love", "romance", "basketball"],
  },
  {
    text: "We loved with a love that was more than love.",
    author: "Edgar Allen Poe",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love isn’t something you find. Love is something that finds you.",
    author: "Loretta Young",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is a juice with many tastes. Some bitter, others sweet. A wine which has few vineyards.",
    author: "Justice, Poetic Justice",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "The practice of love offers no place of safety. We risk loss, hurt, pain. We risk being acted upon by forces outside our control.",
    author: "bell hooks, All About Love: New Visions",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "One is loved because one is loved. No reason is needed for loving.",
    author: "Paulo Coelho, The Alchemist",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is shown more in deeds than in words.",
    author: "Saint Ignatius",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is that condition in which the happiness of another person is essential to your own.",
    author: "Robert A. Heinlein, Stranger in a Strange Land",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "And now these three remain: faith, hope and love. But the greatest of these is love.",
    author: "The Holy Bible: King James Version",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I think... if it is true that there are as many minds as there are heads, then there are as many kinds of love as there are hearts.",
    author: "Leo Tolstoy, Anna Karenina",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is like the wind, you can't see it but you can feel it.",
    author: "Nicholas Sparks, A Walk to Remember",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "In love there are two things: bodies and words.",
    author: "Joyce Carol Oates",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Continue to share your heart with people even if it has been broken.",
    author: "Amy Poehler",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love is such a powerful force. It’s there for everyone to embrace-that kind of unconditional love for all of humankind. That is the kind of love that impels people to go into the community and try to change conditions for others, to take risks for what they believe in.",
    author: "Coretta Scott King",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To love is to recognize yourself in another.",
    author: "Eckhart Tolle",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "To be fully seen by somebody, then, and be loved anyhow - this is a human offering that can border on miraculous.",
    author: "Elizabeth Gilbert",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Love isn't something natural. Rather it requires discipline, concentration, patience, faith, and the overcoming of narcissism. It isn't a feeling, it is a practice.",
    author: "Eric Fromm",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There is always some madness in love. But there is also always some reason in madness.",
    author: "Friedrich Nietzsche",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "There's all kinds of reasons that you fall in love with one person rather than another: Timing is important. Proximity is important. Mystery is important.",
    author: "Helen Fisher",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "Passion makes the world go 'round. Love just makes it a safer place.",
    author: "Ice-T",
    category: categories.love,
    tags: ["love", "romance"],
  },
  {
    text: "I believe in love. I think it just hits you and pulls the rug out from underneath you and, like a baby, demands your attention every minute of the day.",
    author: "Jodi Picoult",
    category: categories.love,
    tags: ["love", "romance"],
  },
];
